---
title: "Hasil Penugasan (debug-friendly)"
format:
  html:
    toc: true
execute:
  echo: false
  warning: false
  error: false
---




# Laporan Submisi Tugas UTS Kelas 01

| No | Nama | NIM | Link URL Hasil Tugas |
|----|------|-----|-----------------------|
| 1 | Ulivia Embun Tresna Wardani | 10322015 | Belum Submit |
| 2 | Daffari Adiyatma | 18222003 | [https://github.com/jackund25/all-about-me](https://github.com/jackund25/all-about-me) |
| 3 | Daffa Ramadhan Elengi | 18222009 | Belum Submit |
| 4 | Jonathan Wiguna | 18222019 | [https://jonathanw33.github.io/all-about-me/](https://jonathanw33.github.io/all-about-me/) |
| 5 | Kezia Caren Cahyadi | 18222041 | Belum Submit |
| 6 | Dama Dhananjaya Daliman | 18222047 | [runningpie.github.io/II2100_All-About-Me/](runningpie.github.io/II2100_All-About-Me/) |
| 7 | Christopher Richard Chandra | 18222057 | Belum Submit |
| 8 | Winata Tristan | 18222061 | [https://stdfreesince03.github.io/18222061-AsesmenII2100](https://stdfreesince03.github.io/18222061-AsesmenII2100) |
| 9 | Muhammad Faiz Atharrahman | 18222063 | [https://all-about-me.faiz.at/](https://all-about-me.faiz.at/) |
| 10 | Muhammad Rafi Dhiyaulhaq | 18222069 | [https://rafidhiyaulh.github.io/all-about-me/](https://rafidhiyaulh.github.io/all-about-me/) |
| 11 | Yoga Putra Pratama | 18222073 | [https://yogaputrap.github.io/all-about-me/](https://yogaputrap.github.io/all-about-me/) |
| 12 | Satria Wisnu Wibowo | 18222087 | [https://peabnj.github.io/all-about-me/](https://peabnj.github.io/all-about-me/) |
| 13 | Muhammad Adli Arindra | 18222089 | Belum Submit |
| 14 | Wisyendra Lunarmalam | 18222095 | [https://wisye.github.io/all-about-me/](https://wisye.github.io/all-about-me/) |
| 15 | Fawwaz Aydin Mustofa | 18222109 | [https://fawwazay11.github.io/all-about-me/](https://fawwazay11.github.io/all-about-me/) |
| 16 | Samuel Franciscus Togar H | 18222131 | [https://sfrans21.github.io/ii2100_all-about-me/](https://sfrans21.github.io/ii2100_all-about-me/) |
| 17 | Hanan Fitra Salam | 18222133 | [https://hananfits.github.io/all-about-me/](https://hananfits.github.io/all-about-me/) |
| 18 | Felissha Dunell Damanik | 18223099 | Belum Submit |
| 19 | Muhammad Dhafin Faidhulhaq | 18223103 | Belum Submit |
| 20 | Nisrina Zakiyah | 18224001 | [https://bellechillguy.github.io/kominter-18224001/](https://bellechillguy.github.io/kominter-18224001/) |
| 21 | Keira Amelie Hanayesha | 18224003 | Belum Submit |
| 22 | Mishael Gilland | 18224005 | Belum Submit |
| 23 | Faizal Ali | 18224007 | [https://github.com/zal1zal/all-about-me & https://github.io/zal1zal/all-about-me](https://github.com/zal1zal/all-about-me & https://github.io/zal1zal/all-about-me) |
| 24 | Keisha Daffa Aryani | 18224009 | [https://keisharyaa.github.io/II2100_Keisha-Daffa/](https://keisharyaa.github.io/II2100_Keisha-Daffa/) |
| 25 | Satria Guna Darma | 18224011 | [https://astebern.github.io/all-about-me/](https://astebern.github.io/all-about-me/) |
| 26 | Salma Az Zahra | 18224015 | [https://salmaazzra.github.io/all-about-me/](https://salmaazzra.github.io/all-about-me/) |
| 27 | Naomi Azzahra | 18224017 | Belum Submit |
| 28 | Evan Nathanael Tanuri | 18224019 | Belum Submit |
| 29 | Muhammad Okto Huzainy | 18224021 | [https://takkko-o.github.io/all-about-me/](https://takkko-o.github.io/all-about-me/) |
| 30 | Ahmad Aditya Ar Rasyid | 18224023 | [https://kenpa1945.github.io/18224023-AsesmenII2100/](https://kenpa1945.github.io/18224023-AsesmenII2100/) |
| 31 | Muhammad Faris Daffa | 18224025 | Belum Submit |
| 32 | Nafhan Shafy Aulia | 18224027 | [https://nafhansa.github.io/all-about-me/](https://nafhansa.github.io/all-about-me/) |
| 33 | Mineva Azzahra | 18224029 | [https://min646.github.io/all-about-me/](https://min646.github.io/all-about-me/) |
| 34 | Daniel Arrigo Manurung | 18224031 | [https://1920xl080.github.io/all-about-me/](https://1920xl080.github.io/all-about-me/) |
| 35 | Rezky Muhammad Hafiz Batubara | 18224033 | [https://skyx59.github.io/18224033-AsesmenII2100/All_About_me/](https://skyx59.github.io/18224033-AsesmenII2100/All_About_me/) |
| 36 | Stella Cometta Febriana | 18224035 | Belum Submit |
| 37 | Indah Ramadhani | 18224037 | [https://indahr118.github.io/all-about-me/](https://indahr118.github.io/all-about-me/) |
| 38 | Luthfi Al Pasha | 18224039 | Belum Submit |
| 39 | Irghi Satya Priangga | 18224041 | [https://hippochld8.github.io/all-about-me-irghisp/](https://hippochld8.github.io/all-about-me-irghisp/) |
| 40 | Aldyto Rafif Abhinaya | 18224043 | [https://aldytorafif05.github.io/18224043_Aldyto-Rafif_UTS-Kominter/](https://aldytorafif05.github.io/18224043_Aldyto-Rafif_UTS-Kominter/) |
| 41 | Muthia Ariesta Anggraeni | 18224045 | Belum Submit |
| 42 | Daniel Benaya Toar Supaath | 18224047 | Belum Submit |
| 43 | Nizham Rafa Lazuardi | 18224049 | [https://nizreal.github.io/all-about-me/](https://nizreal.github.io/all-about-me/) |
| 44 | Belva Charissa Putri Have | 18224051 | [https://belvacharissa.github.io/UTS-Komunikasi-Interpesonal-dan-Publik-/](https://belvacharissa.github.io/UTS-Komunikasi-Interpesonal-dan-Publik-/) |
| 45 | Nathan Pasha Athallah | 18224053 | Belum Submit |
| 46 | Adrian Akhdan Assyauqi | 18224055 | [https://ztackholder.github.io/all-about-me/](https://ztackholder.github.io/all-about-me/) |
| 47 | Levina Nathania Bunardi | 18224057 | Belum Submit |
| 48 | Tiara Kusuma Wardhani | 18224059 | Belum Submit |
| 49 | Riantama Putra | 18224061 | Belum Submit |
| 50 | Yumna Fathonah Kautsar | 18224063 | Belum Submit |
| 51 | Benedicta Sherin Chyntia Putri | 18224065 | [https://benedictasherinn.github.io/II-2100/](https://benedictasherinn.github.io/II-2100/) |
| 52 | Bryant Azraqi Mohammad | 18224067 | Belum Submit |
| 53 | Fikrifalah Muslich | 18224069 | [https://fikrifalah.github.io/18224069/All_About_me/](https://fikrifalah.github.io/18224069/All_About_me/) |
| 54 | Ellaine Juvina | 18224071 | [https://aucloire.github.io/all-about-me/](https://aucloire.github.io/all-about-me/) |
| 55 | Abdullah Ahmad Yusuf | 18224073 | [https://yoeztzy.github.io/all-about-me/](https://yoeztzy.github.io/all-about-me/) |
| 56 | Sherry Eunike | 18224075 | [https://gasukabawang.github.io/all-about-me/](https://gasukabawang.github.io/all-about-me/) |
| 57 | Naufalziyadh Alif Bintang S | 18224077 | [https://github.com/ItsOxiris/all-about-me](https://github.com/ItsOxiris/all-about-me) |
| 58 | Rafi Putra Nugraha | 18224079 | Belum Submit |
| 59 | Illona Nasywa Hannum | 18224081 | [https://buahkol.github.io/all-about-me/](https://buahkol.github.io/all-about-me/) |
| 60 | Antania Hanjani Yustika Putri | 18224083 | [https://hantaniaa.github.io/all-about-me/](https://hantaniaa.github.io/all-about-me/) |
| 61 | Ahmad Rizal Fahmi | 18224085 | [https://lntermezzzo.github.io/about-me/](https://lntermezzzo.github.io/about-me/) |
| 62 | Abhinaya Rajendra Fargaz | 18224087 | [https://about-abhinaya.vercel.app](https://about-abhinaya.vercel.app) |
| 63 | Muhammad Azikra Wira Pratama | 18224089 | [https://awp-confirm.github.io/all-about-me/](https://awp-confirm.github.io/all-about-me/) |
| 64 | Made Krisna Kusuma Wijaya | 18224091 | [https://yaisnaa.github.io/II2100_Krisna-Kusuma/](https://yaisnaa.github.io/II2100_Krisna-Kusuma/) |
| 65 | Kenneth Moses Saragih | 18224093 | [https://kaem-nyoba.github.io/II2100_Kenneth-Moses/](https://kaem-nyoba.github.io/II2100_Kenneth-Moses/) |
| 66 | Sirojul Firdaus | 18224095 | [https://sirojulfirdaus.github.io/kipp-all-about-me/](https://sirojulfirdaus.github.io/kipp-all-about-me/) |
| 67 | Lukman Hakim Syah Ardhana | 18224097 | [https://lukmanhakimsa.github.io/all-about-me/](https://lukmanhakimsa.github.io/all-about-me/) |
| 68 | Muhammad Afif Habiburrahman | 18224099 | [https://github.com/fifiyy/all-about-me](https://github.com/fifiyy/all-about-me) |
| 69 | Jacko Luciano | 18224101 | [jackoluciano.github.io/all-about-me](jackoluciano.github.io/all-about-me) |
| 70 | Haidarrozan Pramasony | 18224103 | [https://oxanovijk.github.io/18224103-Kominter/](https://oxanovijk.github.io/18224103-Kominter/) |
| 71 | Kyan Saktya Diraya | 18224105 | Belum Submit |
| 72 | Laurensius Dani Rendragraha | 18224107 | [https://laurensiusdani.github.io/all-about-me/](https://laurensiusdani.github.io/all-about-me/) |
| 73 | Adriel Nathanael Simatupang | 18224109 | [https://mimumscar.github.io/all-about-me/](https://mimumscar.github.io/all-about-me/) |